### PR TITLE
Add transformed data

### PR DESCRIPTION
**Pull request by dr0i**
Provides transformed data as ntriples. The data lacks address data for now.

### CODE REVIEW

**Comment by fsteeg** [comment]
Since this data format is neither the output nor the input of our code, I think this isn't the right place for it.

If we want to publish this representation for some reason, perhaps the data hub would be more suitable.

**Comment by dr0i** [comment]
ping @acka47 found this could be relevant for documentation of our work.

**Comment by acka47** [comment]
Yes, I don't think we publish this for others to reuse but to document the steps of improving the data transformation...

**Comment by fsteeg** [comment]
But why publish this format and not the one that we actually produce (oer-data) and consume (oer-api)?

**Comment by dr0i** [comment]
After discussion: we will close that pull request without merging. The test data result should be enough to document the status quo/imrpovement of the data.

**Pull request closed without merging**
