### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by dr0i**
Please merge _after_ https://github.com/lobid/lodmill/pull/374 is merged .

### CODE REVIEW

**Comment by fsteeg** [comment]
Tests fail with NullPointerException, see Travis log for details.

Note that 1.0.0 is always considered newer than 1.0.0-SNAPSHOT by Maven, so it does not work well to add stuff and then move from 1.0.0 to 1.0.0-SNAPSHOT. Should be 1.1.0-SNAPSHOT instead. Also an issue in https://github.com/lobid/lodmill/pull/374

**Comment by dr0i** [comment]
Thx, updated that.

**Comment by fsteeg** [comment]
It seems you have force pushed into this branch and thereby overwritten my commit.

Since we now push into branches in the common repo, not in our own fork, we can't do that any longer.

**Comment by dr0i** [comment]
Ah - you are right! That's why I couldn't find your commit ;)

**Pull request merged**
