### PR TITLE
Support queries by country label via separate geonames documents and parent-child queries

### PR DESCRIPTION
**Pull request by fsteeg**
See #98

Deployed to staging: http://staging.api.lobid.org/oer

All fields in the geonames data are used by the filter, so different languages are supported:

http://staging.api.lobid.org/oer?q=*&location=germany
http://staging.api.lobid.org/oer?q=*&location=deutschland
http://staging.api.lobid.org/oer?q=*&location=ドイツ

### CODE REVIEW

**Comment by literarymachine** [comment]
I would have expected queries such as

```
http://staging.api.lobid.org/oer?q=deutschland
```

to deliver results. Not sure if an extra `location`-param is needed here. Interestingly enough, the above query delivers data about geonames-features. Is that correct?

**Comment by fsteeg** [comment]
Since the country labels are not in the actual OER documents but in the geonames documents, the `q=` queries return the geonames documents. The `location=` parameter returns the corresponding OER document (which isn't new BTW but was previously only used for coordinates, see http://staging.api.lobid.org/oer).

**Comment by fsteeg** [comment]
Fix to return only OER resources on `/oer` queries deployed to staging:

http://staging.api.lobid.org/oer?q=deutschland
http://staging.api.lobid.org/oer?q=*&location=deutschland

**Comment by literarymachine** [comment]
> which isn't new BTW but was previously only used for coordinates

Right, I have been using it in that way.

As for the labels in the index: I think that including a country name in a query (q-param) is a fairly common use-case, similar to using an author's name when looking for a resource.

**Comment by fsteeg** [comment]
Deployed implicit addition of `q=` parameter value as `location=` if no `location=` is given.

@literarymachine this should yield the behaviour you expect:

http://staging.api.lobid.org/oer?q=deutschland

**Comment by fsteeg** [comment]
Redeployed to aither, now running on Elasticsearch 1.1.0. Play also running on aither, port 7001. Staging proxy on emphytos updated to point to aither, so this should make no difference for using the OER API.

**Comment by acka47** [comment]
+1

**Pull request merged**
